# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
latex: false
warnings_are_errors: false

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::coveralls()'
  - r: oldrel
  - r: 3.4

